package parse;

terminal String LITBOOL;
terminal String LITINT;
terminal String ID;
terminal        PLUS;
terminal        EQ;
terminal        LPAREN, RPAREN, COMMA;
terminal        BOOL, INT;
terminal        IF, THEN, ELSE;
terminal        LET, IN;

non terminal program;
non terminal exp;

precedence nonassoc EQ;
precedence left     PLUS;

start with program;

program ::=
  exp
;

exp ::=
  LITBOOL
| LITINT
| exp PLUS exp
| exp EQ exp
;
